/**
 * @file Automatically generated by barrelsby.
 */

export * from "./Contacts/LocalizationStringsProviderContract";
export * from "./Contacts/LocalizatorContract";
export * from "./Dependencies/LocalizationModule";
export * from "./Dependencies/ServiceIds";
export * from "./Services/Localizator";
